### ISSUE TITLE
SyntaxError: multiple exception types must be parenthesized

### ISSUE THREAD

**Issue by evanrmurphy** [bootlin/pdf-link-checker#14]
```
% pdf-link-checker my-doc.pdf
  File "/opt/homebrew/bin/pdf-link-checker", line 105
    except urllib2.HTTPError, why:
           ^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized
```

Versions:
- Python 3.11.4
- Mac OS X 13.5.1

**Comment by yegorich** [comment]
You don't seem to have the latest pdf-link-checker version. This error is already fixed in the master branch.

**Comment by michaelopdenacker** [comment]
Thanks @yegorich for checking.
Thanks @evanrmurphy for the report anyway.
Closing the bug.
