### ISSUE TITLE
Installation instructions are outdated

### ISSUE THREAD

**Issue by drittelhacker** [bootlin/pdf-link-checker#15]
Since the PYPI package is frozen on version 1.1.1, which requires Python 2.7, the current _Getting it running_ section in the README is not really helpful anymore. I see two options:

1.  Update the PYPI package to the latest version
2.  Actually rewrite the README to use `pip install git+https://github.com/bootlin/pdf-link-checker.git`

The latter saved my day, when digging it out of #3.

Besides this, many thanks for bringing this helpful tool to Python 3, with the new versions.

**Comment by michaelopdenacker** [comment]
Thanks for the suggestion.
I'm taking option #2.
Fixed by https://github.com/bootlin/pdf-link-checker/commit/ce9129aa762b765a12bfe7b1d42448967894b246
Thanks again
Michael
